basic/models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\form\LicenseForm;
use app\models\db\License;
use app\services\Curl;
use yii\helpers\Json;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {      
        if ($action->id == 'api-create-key-license') {
            $this->enableCsrfValidation = false;
        }
        return true;
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // $form   = new ContactForm();
        // $model  = new ContactMessage();
        // $model->email   ="test@email.com";
        // $model->message = 'Message';
        // $model->date    = new \yii\db\Expression('now()');
        // $model->save();
        return $this->render('index');
    }

    public function actionCreateLicense()
    {
        $formModel = new LicenseForm();

        if ($formModel->load(Yii::$app->request->post()) && $formModel->validate()) {
           
            $licenseName        = $formModel->license_name;  
            $customerName       = $formModel->customer_name;     
            $expiryDate         = $formModel->expiry_date;  
            $licenseDetails     = $formModel->license_details; 

            $requestURL  = 'http://localhost/' . Yii::$app->homeUrl . '/api/create-license';
            $requestData = ['name' => $customerName, 'date' => $expiryDate];
            $response    = Curl::callAPI(Curl::POST, $requestURL, $requestData);

            if ($response->code===201) {

                $data           = Json::decode($response->body);     
                $licenseNumber  = $data['message']['number'];
                $licenseKey     = $data['message']['key'];

                $license                    = new License();
                $license->license_name      = $licenseName;
                $license->customer_name     = $customerName;
                $license->expiry_date       = $expiryDate;
                $license->license_details   = $licenseDetails;
                $license->license_number    = $licenseNumber;
                $license->license_key       = $licenseKey;
                $license->creation_date     = new \yii\db\Expression('now()');
                $license->save();
    
               Yii::$app->session->setFlash('licenseFormSubmitted');
               return $this->refresh();
            }
        }

        return $this->render(
            'create-license',
            [
                'formModel' => $formModel,
            ]
        );
    }

    public function actionLicenseItems()
    {
        return $this->render(
            'license-items',
            [
                'licenseItems' => License::find()->all(),
            ]
        );
    }

    public function actionApiCreateKeyLicense()
    {
        $this->layout = '';
        if (Yii::$app->request->isPost) {
            $name 	= Yii::$app->request->post("name", null);
            $date 	= Yii::$app->request->post("date", null);

            // echo Json::encode(['number' => rand(100, 10000000), 'key' => sha1(mt_rand())]);

            return \Yii::createObject([
                'class'         => 'yii\web\Response',
                'format'        => \yii\web\Response::FORMAT_JSON,
                'statusCode'    => 201,
                'data' => [
                    'message'   => ['number' => rand(100, 10000000), 'key' => sha1(mt_rand())],
                    'code'      => 201,
                ],
            ]);
        } else {
            return \Yii::createObject([
                'class'         => 'yii\web\Response',
                'format'        => \yii\web\Response::FORMAT_JSON,
                'statusCode'    => 405,
                'data' => [
                    'message'   => 'Method not allowed',
                    'code'      => 405,
                ],
            ]);
        }
    }
}

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'License Items', 'url' => ['/site/license-items']],
            ['label' => 'Create License', 'url' => ['/site/create-license']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

basic/views/site/create-license.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'License';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('licenseFormSubmitted')): ?>

        <div class="alert alert-success">
            License created.
        </div>

    <?php else: ?>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'license-form']); ?>

                    <?= $form->field($formModel, 'license_name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($formModel, 'customer_name') ?>

                    <?= $form->field($formModel, 'expiry_date')->widget(
                                                                        \yii\jui\DatePicker::classname(), 
                                                                        [
                                                                            'dateFormat'    => 'yyyy-MM-dd',
                                                                            'options'       => [ 'class' => 'form-control', 'readonly' => 'readonly']
                                                                        ]
                                                                    ); ?>

                    <?= $form->field($formModel, 'license_details')->textarea(['rows' => 6]) ?>

                    <?= $form->field($formModel, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

basic/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Welcome';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Welcome!</h1>
    </div>

    <div class="body-content">

        <div class="row">
 
        </div>

    </div>
</div>

basic/views/site/license-items.php
<?php

/* @var $this yii\web\View */

$this->title = 'License Items';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>License Items!</h1>
    </div>

    <div class="body-content">

        <div class="row">
        <ul>
            <?php
                foreach ($licenseItems as $licenseItem) {

                    echo '<li>'  . $licenseItem->license_name . '</li>';
                }
            ?>
            </ul>
        </div>

    </div>
</div>

basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>